### ISSUE TITLE
Window clipping on AwesomeWM

### ISSUE THREAD

**Issue by nathansCodes** [allusive-dev/compfy#41]
**What is the issue**
Windows get clipped with slide animations and on sudden size changes on awesomewm

**What did you expect**
No clipping, just sliding windows

**Relevant Images or Videos:**

https://github.com/allusive-dev/compfy/assets/99505972/5dc88d12-7dd6-4184-9474-7a036420301c

(see bottom of windows)

https://github.com/allusive-dev/compfy/assets/99505972/1126a586-fe75-4cfa-849d-bbd9b1297df0

**Your configuration**
[compfy.conf.txt](https://github.com/allusive-dev/compfy/files/13380542/compfy.conf.txt)

**Package Version:** 1.6.6
**Build Method:** as described in README
**WM:** awesome

**Comment by naan187** [comment]
I also wanna mention that there are some more issues with animations on awesomewm with compfy (that have already existed with picom-pijulius, these are not your fault :) ), I have just been lazy and not submitting issues about those

**Comment by allusive-dev** [comment]
Hey @naan187 
I'm sorry about all these issues. AwesomeWM looks like it's going to be my Arch nemesis haha.
The first video you sent is pretty normal since the how could i say it, "performance of the completion" of the animations is entirely reliant on each users system, different systems just react differently. 

The second video however is quite different, I see that when a new window is opened the compositor makes space in the wrong spot causing the new window to jank itself and the other window.

I'll install Awesome and do some testing soon. I won't be able to get to it today though sorry.

**Comment by naan187** [comment]
What exactly do you mean with "performance of the completion"? I know of nothing that I have configured myself that could be causing these issues. Even if I delete all the lines in my compfy config except the one that sets the slide-up animation, windows still get clipped instead of sliding in from the bottom of the screen.

**Comment by allusive-dev** [comment]
@naan187

**Comment by allusive-dev** [comment]
I did not mean to close that. GitHub is lagging like crazy

**Comment by allusive-dev** [comment]
@naan187 
I have done some testing on AwesomeWM but I can't replicate the issue.
Would you be able to send your picom configuration and possibly Awesome configuration if you want to?

**Comment by naan187** [comment]
I did send my config in the original post. 
Or if you mean my picom-pijulius config, you can find that in [here](https://github.com/naan187/.dotfiles/blob/main/picom/picom.conf).
And I don't think you want to look through my awesome config, since it's more like a whole codebase rather than a simple config file

**Comment by allusive-dev** [comment]
> And I don't think you want to look through my awesome config, since it's more like a whole codebase rather than a simple config file

No worries I understand.
I'll do some testing with your Compfy config soon and get back to you.

**Comment by allusive-dev** [comment]
Hey @naan187 
Very sorry I have been quite busy recently. 
I'll try to do some testing either today or tomorrow!

**Comment by allusive-dev** [comment]
Hi @naan187
Sorry I have not been able to find enough time to do any more testing.
I'm very sorry I know it's been quite a while now but I will try to get to it asap.

**Comment by naan187** [comment]
That's fine, take all the time you need.
It's not a major issue for me, so waiting isn't really a problem

**Comment by naan187** [comment]
@allusive-dev any updates? You don't seem to be very active anymore
